from .home import Home
from .login import Login
from .signup import Signup
from .login import logout
from .cart import Cart
from .wishlist import Wishlist
from .checkout import Checkout
from .order import OrderView
from .addproduct import AddView
